Better 0.2.0
Raptacon/Robot-2022 pull request #135
Opened 2022-03-25 18:30 UTC by ManiacMoustache

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Steps to Test
1. Test hopper/loader logic and shooting

## Changelog
Removed hopper backdown and slowed down speeds.
Raised drivetrain multiplier to move faster

## Why?
To shoot and drive faster

2022-03-25 19:22 UTC, ChrisHirsch requested changes
Tunables all look good
Remove the commented code

2022-03-25 19:22 UTC, ChrisHirsch commented on components/Actuators/HighLevel/loaderLogic.py
> +        # ballCount = self.ballCounter.getBallCount()
Remove comments

2022-03-26 14:14 UTC, hell0w0rld2 approved these changes

2022-03-26 14:40 UTC, ChrisHirsch requested changes
Unless needed, lets remove the commented code and *especially* consider removing thowing an error log every frame. This logs back at the driver station right?

2022-03-26 14:40 UTC, ChrisHirsch commented on components/Actuators/HighLevel/shooterLogic.py
> +        logging.error("1: %s vs %s, 2: %s vs %s", shootSpeed1, self.shooterMotor1Encoder.getVelocity(), shootSpeed2, self.shooterMotor2Encoder.getVelocity())
Won't this log (and do getVelocity()) on every frame? Could this be what's slowing us down?

2022-03-26 14:50 UTC, ManiacMoustache commented
good to go

2022-03-26 15:09 UTC, ChrisHirsch approved these changes
+💯 Go kill it!

2022-07-13 23:59 UTC, merged