Smoke test
Raptacon/Robot-2022 pull request #34
Opened 2022-01-27 01:55 UTC by hell0w0rld2

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Steps to Test
[ Describe how to run your AUTOMATED TESTS and any manual tests that may be need to prove your fix/feature ]
1.  Resets the estimated distance traveled
2. Drives the robot forwards about 100 inches
3. Runs the intake, hopper, and shooter motors in that order
4. Has the user hold up a red ball to the color sensor
5. Has the user break each of the break sensors

## Changelog

A brief description of the problem statement. 

- This is a smoke test to run through to see if each component on the robot is working. This is to be done before getting into the queue.

Explain the technical implementation of what you're doing.

- This could help the team figure out if any electrical components are broken before going into a match.

Explain why you're making this change and what benefits from it. 

- We would be able to see what, if anything, is broken before going into a match. An example of this would be the break sensors at the scrimmage.

## Automation
Issue: <issue-XX> Describe the issue you're working on here so it ties to the issue and Kanban.

2022-01-29 17:50 UTC, ChrisHirsch commented on autonomous/smokeTest.py
> +    """
Commented because it's not quite ready..more of an example

2022-01-29 17:51 UTC, ChrisHirsch submitted a review, later dismissed
+1 👍 🥇

2022-01-29 17:59 UTC, ManiacMoustache requested changes
We should have log errors for when the checks pass as well, so if they have false positives we know.

2022-02-05 00:59 UTC, ManiacMoustache approved these changes
gg

2022-02-05 18:18 UTC, ManiacMoustache approved these changes
looks good

2022-02-05 18:20 UTC, Leaf-life approved these changes
good

2022-02-05 18:20 UTC, merged

2022-02-05 18:20 UTC, tuffinmuffin approved these changes