Drivetrain abstractor
Raptacon/Robot-2022 pull request #35
Opened 2022-01-27 02:35 UTC by ManiacMoustache

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Steps to Test
1. Get a robot with a drivetrain
2. Enable an autonomous component that uses the drivetrain during teleop
3. Use the drive controller while the component is running

If you can drive the robot while the component is running, it works

## Changelog

We had a poor way of handling who gets the drivetrain.

## What?

Added a new component to act as a controller of who gets control of the drivetrain. Right now it's implemented in all autonomous components that use the drivetrain. It's not as complicated as it could be, but there's always the potential for more later.

## Why?
Because previously we'd have issues with who controls the drivetrain

## Automation
(We don't have an issue for this)

2022-01-29 01:22 UTC, ChrisHirsch requested changes
Let me know if you need help with the abstraction for tank (or any specific drive)

2022-01-29 01:22 UTC, ChrisHirsch commented on components/turnToAngle.py
> +            self.driveTrainHandler.setTank(self, -1 * self.speed, self.speed)
Still hardcoded to setTank? This should be abstracted now right?

2022-01-29 01:22 UTC, ChrisHirsch commented on components/turnToAngle.py
> +            self.driveTrainHandler.setTank(self, self.speed, -1 * self.speed)
Still hardcoded to setTank? This should be abstracted now right?

2022-01-29 01:22 UTC, ChrisHirsch commented on components/turnToAngle.py
> +            self.driveTrainHandler.setTank(self, -1 * self.speed, self.speed)
If we need the correct handler, considering abstracting that and passing it in?

2022-01-29 01:22 UTC, ChrisHirsch commented on robot.py
> +    controllerDeadzone = tunable(.06)
Comment on what this is?

2022-02-12 16:56 UTC, hell0w0rld2 approved these changes
👍

2022-02-17 02:59 UTC, hell0w0rld2 approved these changes
👍

2022-02-17 03:23 UTC, ChrisHirsch approved these changes
Yep..it's a good start! +1

2022-02-17 03:23 UTC, merged