Auto align rewrite
Raptacon/Robot-2022 pull request #6
Opened 2022-01-15 01:25 UTC by Leaf-life

fixed the state michine to use idiling and simplified the logic for calculating the degrees from alignment to include less if statments

2022-01-15 22:31 UTC, Team3200 commented
I'm sorry
-Caiden

2022-01-20 01:23 UTC, ManiacMoustache requested changes
Better than my original version

2022-01-20 01:23 UTC, ManiacMoustache commented on components/autoAlign.py
> +            log.info("Autoalign complete")
Line 101 will run every loop, which won't be accurate.

2022-01-20 01:23 UTC, ManiacMoustache commented on components/autoAlign.py
> +                    self.next_state("adjust_self")
This causes an infinite loop (which we stop in robot.py, but it's better if the component exits by itself)

2022-01-22 20:26 UTC, ManiacMoustache submitted a review, later dismissed
+1
Better than mine

2022-01-22 20:30 UTC, hell0w0rld2 submitted a review, later dismissed
Approved

2022-01-27 01:21 UTC, ManiacMoustache approved these changes
+1 Recent commits have not changed my opinion

2022-01-29 03:01 UTC, hell0w0rld2 approved these changes

2022-01-29 03:03 UTC, merged