Controller remap
Raptacon/Robot-2022 pull request #73
Opened 2022-03-03 01:18 UTC by hell0w0rld2

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Associated Issue(s)
Issue: <#X or issue-XX > [REMOVE THIS WHEN DONE Describe the issue you're working on here so it ties to the issue and Kanban (IMPORTANT FOR TRACKING). Make sure to create an issue if one doesn't already exist! ]

## Steps to Test
[ Describe how to run your AUTOMATED TESTS and any manual tests that may be need to prove your fix/feature REMOVE THIS WHEN DONE]
1. [First Step]
2. [Second Step]
3. [and so on...]

## Changelog

## What?
Remaps the controllers to give full intake control to main and shooting to the aux. It also allows the turret to be manually controled without calibration

## Why?

Making the way the controllers used better and fixes problems that come up when the turret isn't calibrated.

2022-03-03 01:20 UTC, ManiacMoustache submitted a review, later dismissed
I wrote most of this code too, I guess

2022-03-03 02:14 UTC, ChrisHirsch requested changes

2022-03-03 02:14 UTC, ChrisHirsch commented on components/Actuators/AutonomousControl/autoShoot.py
> +        log.error("Using default %s", configPath)
We probably want to "crash" if we can't find the config right? so re-raise e?

2022-03-05 02:15 UTC, hell0w0rld2 commented on components/Actuators/HighLevel/feederMap.py
> +            if self.xboxMap.getDriveLeftTrig() > 0 and self.xboxMap.getDriveRightTrig() == 0:
In theory, we'd have a better system for handling axis inputs and they'd be readable in the code, but yeah. For now, it's hide and seek.

2022-03-05 03:31 UTC, merged